[[news]]
date = "2026-04"
content = "Started my PhD studies in the Department of Physics at the University of Tokyo."
[[news]]
date = "2026-03"
content = "Graduated with a Master of Science in Physics from the University of Tokyo and started my PhD studies in the Department of Physics."
[[news]]
date = "2026-03"
content = "Our preprint, \"Exactly Solvable Disorder-free Quantum Breakdown Model: Spectrum, Thermodynamics, and Dynamics,\" was posted on arXiv."

