[[news]]
date = "2026-04"
content = "東京大学大学院 理学系研究科 物理学専攻 の博士課程に進学しました。"

[[news]]
date = "2026-03"
content = "東京大学大学院 理学系研究科 で 物理学修士号 を取得しました。"

[[news]]
date = "2026-03"
content = "私たちの論文「Exactly Solvable Disorder-free Quantum Breakdown Model: Spectrum, Thermodynamics, and Dynamics」が arXiv に公開されました。"