[[news]]
date = "2026-04"
content = "开始在东京大学物理学系攻读博士课程。"

[[news]]
date = "2026-03"
content = "从东京大学获得物理学硕士学位，并进入物理学系博士课程。"

[[news]]
date = "2026-03"
content = "我们的预印本《Exactly Solvable Disorder-free Quantum Breakdown Model: Spectrum, Thermodynamics, and Dynamics》已发表于 arXiv。"
